"""Server-side PDF report generation (reportlab).

Renders a clinical summary PDF from real workspace data: a patient header, the visit diagnosis,
and a table of computed measurements (tool + value + unit). Pure function of its inputs — no I/O,
no PHI logging — so it's easy to unit-test and safe to run in a worker later.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_ACCENT = colors.HexColor("#2563eb")


def _fmt_result(result: dict | None) -> str:
    """Format a measurement result blob ({value, unit}) for display."""
    if not result:
        return "—"
    value = result.get("value")
    unit = result.get("unit") or ""
    if value is None:
        # Fall back to any human-readable field the tool stored.
        return str(result.get("display") or result.get("label") or "—")
    if isinstance(value, (int, float)):
        return f"{round(value, 2)} {unit}".strip()
    return f"{value} {unit}".strip()


def render_report_pdf(
    *,
    patient: dict,
    diagnosis: str | None,
    measurements: list[dict],
    title: str | None = None,
) -> bytes:
    """Build the report PDF and return its bytes.

    `patient` carries name/age/gender/dob/contact; `measurements` is a list of
    {tool_key, result, ...} dicts (the persisted context measurements).
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm, topMargin=18 * mm, bottomMargin=18 * mm,
        title=title or "SpineSurge Report",
    )
    styles = getSampleStyleSheet()
    h1 = styles["Title"]
    h1.textColor = _ACCENT
    normal = styles["Normal"]
    small = styles["BodyText"]

    story: list = []
    story.append(Paragraph(title or "Spine Assessment Report", h1))
    generated = datetime.now(UTC).strftime("%b %d, %Y %H:%M UTC")
    story.append(Paragraph(f"Generated {generated}", small))
    story.append(Spacer(1, 8 * mm))

    # Patient block.
    age = patient.get("age")
    sex = patient.get("gender") or "—"
    demo = f"{age}{sex}" if age else sex
    rows = [
        ["Patient", patient.get("name") or "—"],
        ["Age / Sex", demo],
        ["DOB", patient.get("dob") or "—"],
        ["MRN / Contact", patient.get("contact") or "—"],
        ["Diagnosis", diagnosis or "—"],
    ]
    info = Table(rows, colWidths=[40 * mm, 120 * mm])
    info.setStyle(
        TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
        ])
    )
    story.append(info)
    story.append(Spacer(1, 8 * mm))

    # Measurements table.
    story.append(Paragraph("Measurements", styles["Heading2"]))
    story.append(Spacer(1, 2 * mm))
    if measurements:
        data = [["#", "Tool", "Result"]]
        for i, m in enumerate(measurements, start=1):
            data.append([str(i), str(m.get("tool_key") or "—"), _fmt_result(m.get("result"))])
        table = Table(data, colWidths=[12 * mm, 88 * mm, 60 * mm], repeatRows=1)
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), _ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ])
        )
        story.append(table)
    else:
        story.append(Paragraph("No measurements recorded for this assessment.", normal))

    story.append(Spacer(1, 12 * mm))
    story.append(Paragraph(
        "This report was generated by SpineSurge Pro. Values are computed from the recorded "
        "workspace measurements and should be clinically reviewed.", small,
    ))

    doc.build(story)
    return buf.getvalue()
