import { ReportConfig, ReportDocumentSettings, ReportSectionConfig } from "@/lib/store/types";

/**
 * The report is a live summary of the whole case. Each section only renders
 * when its source has content (no measurements → no Assessment table, no
 * Image B → no Comparison, …).
 */
export const DEFAULT_REPORT_SECTIONS: ReportSectionConfig[] = [
    { id: "patient_summary",   type: "patient_summary",   enabled: true, order: 0, title: "Patient Summary",  description: "Demographics and diagnosis" },
    { id: "images",            type: "images",            enabled: true, order: 1, title: "Images",           description: "Annotated case image (and comparison image)" },
    { id: "measurement_table", type: "measurement_table", enabled: true, order: 2, title: "Assessment",       description: "Measurements from the Assessment tab" },
    { id: "surgical_plan",     type: "surgical_plan",     enabled: true, order: 3, title: "Surgical Plan",    description: "Saved plans: image, targets, preop vs plan" },
    { id: "compare_table",     type: "compare_table",     enabled: true, order: 4, title: "Comparison",       description: "Image A vs Image B from Compare" },
    { id: "notes",             type: "notes",             enabled: true, order: 5, title: "Clinical Notes",   description: "Free-text notes" },
];

export const DEFAULT_REPORT_DOCUMENT: ReportDocumentSettings = {
    title: "Spine Surgical Planning Report",
    institution: "",
    department: "Department of Spine Surgery",
    pageSize: "a4",
    orientation: "portrait",
    accentColor: "#FF453A",
    fontScale: 1,
    showPageNumbers: true,
    footerText: "Generated by SpineSurge Pro",
};

export const getDefaultReportConfig = (): ReportConfig => ({
    sections: DEFAULT_REPORT_SECTIONS.map((s) => ({ ...s })),
    document: { ...DEFAULT_REPORT_DOCUMENT },
});

/** Fill in anything missing from older saved configs (new sections / document settings). */
export function normalizeReportConfig(cfg: ReportConfig | undefined | null): ReportConfig {
    if (!cfg) return getDefaultReportConfig();
    const known = new Set(cfg.sections.map((s) => s.id));
    const legacy = new Set(['osteotomies', 'instrumentation', 'alignment_summary']);
    const sections = [
        ...cfg.sections.filter((s) => !legacy.has(s.type)),
        ...DEFAULT_REPORT_SECTIONS.filter((d) => !known.has(d.id)).map((d) => ({ ...d, order: 100 + d.order })),
    ].sort((a, b) => a.order - b.order).map((s, i) => ({ ...s, order: i }));
    return { ...cfg, sections, document: { ...DEFAULT_REPORT_DOCUMENT, ...(cfg.document ?? {}) } };
}
